def o(r):
    for i in range (500):
        turtle.forward(r)
        turtle.left(0.72)

def d(r):
    for i in range (250):
        turtle.forward(r)
        turtle.right(0.72)

import turtle
turtle.shape('turtle')
turtle.speed(0)
turtle.fillcolor('yellow')
turtle.begin_fill()
o(2)
turtle.end_fill()
turtle.penup()
turtle.left(90)
turtle.forward(260)
turtle.left(90)
turtle.forward(70)
turtle.pendown()
turtle.fillcolor('blue')
turtle.begin_fill()
o(0.3)
turtle.end_fill()
turtle.penup()
turtle.left(180)
turtle.forward(140)
turtle.left(180)
turtle.pendown()
turtle.begin_fill()
o(0.3)
turtle.end_fill()
turtle.penup()
turtle.forward(70)
turtle.left(90)
turtle.forward(90)
turtle.width(5)
turtle.pendown()
turtle.forward(60)
turtle.penup()
turtle.left(90)
turtle.forward(80)
turtle.right(90)
turtle.color('red')
turtle.pendown()
d(1.0053)
